export const COUNTRY_CODES = [
  { country: 'Afghanistan', dialCode: '+93' },
  { country: 'Albania', dialCode: '+355' },
  { country: 'Algeria', dialCode: '+213' },
  { country: 'Argentina', dialCode: '+54' },
  { country: 'Australia', dialCode: '+61' },
  { country: 'Austria', dialCode: '+43' },
  { country: 'Bangladesh', dialCode: '+880' },
  { country: 'Belgium', dialCode: '+32' },
  { country: 'Bhutan', dialCode: '+975' },
  { country: 'Brazil', dialCode: '+55' },
  { country: 'Canada', dialCode: '+1' },
  { country: 'Chile', dialCode: '+56' },
  { country: 'China', dialCode: '+86' },
  { country: 'Colombia', dialCode: '+57' },
  { country: 'Croatia', dialCode: '+385' },
  { country: 'Czech Republic', dialCode: '+420' },
  { country: 'Denmark', dialCode: '+45' },
  { country: 'Egypt', dialCode: '+20' },
  { country: 'Ethiopia', dialCode: '+251' },
  { country: 'Finland', dialCode: '+358' },
  { country: 'France', dialCode: '+33' },
  { country: 'Germany', dialCode: '+49' },
  { country: 'Greece', dialCode: '+30' },
  { country: 'Hong Kong', dialCode: '+852' },
  { country: 'Hungary', dialCode: '+36' },
  { country: 'Iceland', dialCode: '+354' },
  { country: 'India', dialCode: '+91' },
  { country: 'Indonesia', dialCode: '+62' },
  { country: 'Iran', dialCode: '+98' },
  { country: 'Iraq', dialCode: '+964' },
  { country: 'Ireland', dialCode: '+353' },
  { country: 'Israel', dialCode: '+972' },
  { country: 'Italy', dialCode: '+39' },
  { country: 'Japan', dialCode: '+81' },
  { country: 'Jordan', dialCode: '+962' },
  { country: 'Kenya', dialCode: '+254' },
  { country: 'Kuwait', dialCode: '+965' },
  { country: 'Malaysia', dialCode: '+60' },
  { country: 'Mexico', dialCode: '+52' },
  { country: 'Morocco', dialCode: '+212' },
  { country: 'Nepal', dialCode: '+977' },
  { country: 'Netherlands', dialCode: '+31' },
  { country: 'New Zealand', dialCode: '+64' },
  { country: 'Nigeria', dialCode: '+234' },
  { country: 'Norway', dialCode: '+47' },
  { country: 'Oman', dialCode: '+968' },
  { country: 'Pakistan', dialCode: '+92' },
  { country: 'Philippines', dialCode: '+63' },
  { country: 'Poland', dialCode: '+48' },
  { country: 'Portugal', dialCode: '+351' },
  { country: 'Qatar', dialCode: '+974' },
  { country: 'Romania', dialCode: '+40' },
  { country: 'Russia', dialCode: '+7' },
  { country: 'Saudi Arabia', dialCode: '+966' },
  { country: 'Singapore', dialCode: '+65' },
  { country: 'South Africa', dialCode: '+27' },
  { country: 'South Korea', dialCode: '+82' },
  { country: 'Spain', dialCode: '+34' },
  { country: 'Sri Lanka', dialCode: '+94' },
  { country: 'Sweden', dialCode: '+46' },
  { country: 'Switzerland', dialCode: '+41' },
  { country: 'Thailand', dialCode: '+66' },
  { country: 'Turkey', dialCode: '+90' },
  { country: 'UAE', dialCode: '+971' },
  { country: 'UK', dialCode: '+44' },
  { country: 'USA', dialCode: '+1' },
  { country: 'Ukraine', dialCode: '+380' },
  { country: 'Vietnam', dialCode: '+84' },
  { country: 'Zimbabwe', dialCode: '+263' },
];
